package licenseheader_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/blairham/pre-commit-hooks/internal/licenseheader"
)

func write(t *testing.T, dir, name, body string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

const good = `// SPDX-FileCopyrightText: 2026 Jane Doe
// SPDX-License-Identifier: Apache-2.0

package p
`

func TestCheck(t *testing.T) {
	opts := licenseheader.Default()
	opts.License = "Apache-2.0"

	tests := []struct {
		name, body string
		wantReason string // empty: no violation
	}{
		{"complete header", good, ""},
		{"no header at all", "package p\n", "missing SPDX-License-Identifier:"},
		{
			"license but no copyright",
			"// SPDX-License-Identifier: Apache-2.0\n\npackage p\n",
			"missing SPDX-FileCopyrightText:",
		},
		{
			"wrong license is caught, not just absence",
			"// SPDX-FileCopyrightText: 2026 Jane Doe\n// SPDX-License-Identifier: MIT\n\npackage p\n",
			`declares "MIT", want "Apache-2.0"`,
		},
		{
			// The generator owns these lines; rewriting them every time it
			// runs is churn, so they are exempt rather than failing.
			"generated files are exempt",
			"// Code generated by stringer. DO NOT EDIT.\n\npackage p\n",
			"",
		},
		{
			// A build constraint legally precedes everything but comments,
			// so the header sits above it and must still be found.
			"header above a build constraint",
			"// SPDX-FileCopyrightText: 2026 Jane Doe\n// SPDX-License-Identifier: Apache-2.0\n\n//go:build linux\n\npackage p\n",
			"",
		},
		{
			// Beyond -head lines, so it does not count: a header buried in
			// the body is not a header.
			"tag too far down the file",
			"package p\n\n\n\n\n\n// SPDX-License-Identifier: Apache-2.0\n",
			"missing SPDX-License-Identifier:",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			p := write(t, dir, "a.go", tc.body)

			got, err := licenseheader.Check(dir, []string{p}, opts)
			if err != nil {
				t.Fatal(err)
			}
			if tc.wantReason == "" {
				if len(got) != 0 {
					t.Fatalf("want no violation, got %v", got)
				}
				return
			}
			if len(got) != 1 {
				t.Fatalf("want 1 violation, got %d: %v", len(got), got)
			}
			if got[0].Reason != tc.wantReason {
				t.Errorf("reason = %q, want %q", got[0].Reason, tc.wantReason)
			}
		})
	}
}

func TestCheckAnyLicenseAccepted(t *testing.T) {
	// An empty License means a repository with mixed licensing still gets
	// the "there must be *a* header" guarantee.
	opts := licenseheader.Default()
	dir := t.TempDir()
	p := write(t, dir, "a.go", "// SPDX-FileCopyrightText: x\n// SPDX-License-Identifier: MIT\n\npackage p\n")

	got, err := licenseheader.Check(dir, []string{p}, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Fatalf("want no violation, got %v", got)
	}
}

func TestCheckWalksTreeAndFiltersExtensions(t *testing.T) {
	opts := licenseheader.Default()
	opts.License = "Apache-2.0"

	dir := t.TempDir()
	write(t, dir, "ok.go", good)
	write(t, dir, "bad.go", "package p\n")
	write(t, dir, "notgo.md", "# no header here\n")
	write(t, dir, "vendor/dep.go", "package dep\n")
	write(t, dir, ".git/hook.go", "package g\n")

	got, err := licenseheader.Check(dir, nil, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("want 1 violation, got %d: %v", len(got), got)
	}
	if filepath.Base(got[0].Path) != "bad.go" {
		t.Errorf("flagged %s, want bad.go", got[0].Path)
	}
}

func TestExclude(t *testing.T) {
	opts := licenseheader.Default()
	opts.Exclude = []string{"*_gen.go"}

	dir := t.TempDir()
	p := write(t, dir, "thing_gen.go", "package p\n")

	got, err := licenseheader.Check(dir, []string{p}, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Fatalf("excluded file was still flagged: %v", got)
	}
}

func TestFixInsertsAboveBuildConstraint(t *testing.T) {
	opts := licenseheader.Default()
	opts.License = "Apache-2.0"
	opts.CopyrightText = "2026 Jane Doe"

	dir := t.TempDir()
	p := write(t, dir, "a.go", "//go:build linux\n\npackage p\n")

	fixed, err := licenseheader.Fix(dir, []string{p}, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(fixed) != 1 {
		t.Fatalf("want 1 fixed, got %v", fixed)
	}

	body, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	want := "// SPDX-FileCopyrightText: 2026 Jane Doe\n" +
		"// SPDX-License-Identifier: Apache-2.0\n" +
		"\n//go:build linux\n\npackage p\n"
	if string(body) != want {
		t.Errorf("after fix:\n%q\nwant:\n%q", body, want)
	}

	// The constraint must still be followed by a blank line before the
	// package clause, or the file no longer builds.
	if !strings.Contains(string(body), "//go:build linux\n\npackage p") {
		t.Error("build constraint lost its trailing blank line")
	}

	// And the result must now pass its own check.
	got, err := licenseheader.Check(dir, []string{p}, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Errorf("file still fails after fix: %v", got)
	}
}

func TestFixRefusesWithoutEnoughInformation(t *testing.T) {
	dir := t.TempDir()
	p := write(t, dir, "a.go", "package p\n")

	t.Run("no license", func(t *testing.T) {
		opts := licenseheader.Default()
		opts.CopyrightText = "2026 Jane Doe"
		if _, err := licenseheader.Fix(dir, []string{p}, opts); err == nil {
			t.Error("want an error when no license identifier is configured")
		}
	})

	t.Run("no copyright text", func(t *testing.T) {
		opts := licenseheader.Default()
		opts.License = "Apache-2.0"
		if _, err := licenseheader.Fix(dir, []string{p}, opts); err == nil {
			t.Error("want an error when a copyright line is required but has no text")
		}
	})
}
